import loading_event from "../images/loading_event.jpg";
import completed_event from "../images/completed_event.jpg";

const upcommingcolorcode = "#f37022";
const completedcolorcode = "#005DA3";

export const eventdata = [
  {
    title: "WSRO Regionals",
    startdate: "February 24, 2024",
    enddate: "February 24, 2024",
    location: "Jaipur",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "WSRO Regionals",
    startdate: "February 24, 2024",
    enddate: "February 24, 2024",
    location: "Jaipur",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "WSRO Regionals",
    startdate: "February 3, 2024",
    enddate: "February 3, 2024",
    location: "Pune",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "FTC",
    startdate: "January 27, 2024",
    enddate: "January 28, 2023",
    location: "Pune",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "Vex Competition",
    startdate: "January 20, 2024",
    enddate: "January 21, 2024",
    location: "Garodia School, Mumbai",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "31st Convergence India Expo",
    startdate: "January 17, 2024",
    enddate: "January 19, 2024",
    location: "Delhi",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "Rotary Club Fun Street",
    startdate: "December 23, 2023",
    enddate: "December 23, 2023",
    location: "Powai",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "Annual Function",
    startdate: "December 20, 2023",
    enddate: "December 20, 2023",
    location: "GK Gurukul, Pune",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "World Kid Expo Event",
    startdate: "December 16, 2023",
    enddate: "December 17, 2023",
    location: "NESCO, Mumbai",
    color: upcommingcolorcode,
    status: "Upcoming",
    status_img: loading_event,
  },
  {
    title: "Clara Global Event",
    startdate: "December 10, 2023",
    enddate: "December 10, 2023",
    location: "Pune",
    color: completedcolorcode,
    status: "Completed",
    status_img: completed_event,
  },
  {
    title: "Finland International Event",
    startdate: "December 9, 2023",
    enddate: "December 9, 2023",
    location: "Pune",
    color: completedcolorcode,
    status: "Completed",
    status_img: completed_event,
  },
  {
    title: "ESFE Exhibition",
    startdate: "December 4, 2023",
    enddate: "December 6, 2023",
    location: "BKC MMRDA, Mumbai",
    color: completedcolorcode,
    status: "Completed",
    status_img: completed_event,
  },
  {
    title: "Robotics Competition",
    startdate: "December 2, 2023",
    enddate: "December 2, 2023",
    location: "Trinity Interschool",
    color: completedcolorcode,
    status: "Completed",
    status_img: completed_event,
  },
  {
    title: "Principal Event",
    startdate: "December 2, 2023",
    enddate: "December 2, 2023",
    location: "Gurugram",
    color: completedcolorcode,
    status: "Completed",
    status_img: completed_event,
  },
  {
    title: "Robotic Workshop",
    startdate: "December 2, 2023",
    enddate: "December 2, 2023",
    location: "Cambria International School, Kalyan",
    color: completedcolorcode,
    status: "Completed",
    status_img: completed_event,
  },
  {
    title: "Eldrok",
    startdate: "December 1, 2023",
    enddate: "December 1, 2023",
    location: "Jaipur",
    color: completedcolorcode,
    status: "Completed",
    status_img: completed_event,
  },
];
